#ifndef __SOUND_CONFIG_H__
#define __SOUND_CONFIG_H__

// background
#define SOUND_BACKGROUND_ACADEMY	1
#define SOUND_BACKGROUND_BOSS		2
#define SOUND_BACKGROUND_DARKELF	3
#define SOUND_BACKGROUND_DEVIL		4
#define SOUND_BACKGROUND_DWARF		5
#define SOUND_BACKGROUND_ELF		6
#define SOUND_BACKGROUND_FAIL		7
#define SOUND_BACKGROUND_HUMAN		8
#define SOUND_BACKGROUND_MAIN		9
#define SOUND_BACKGROUND_SUCCEED	10
#define SOUND_BACKGROUND_UNDEAD		11


//sound effect
#define SOUND_BUTTON				12
#define SOUND_EQUIP_UPGRADE			13
#define SOUND_NORMAL_TOWER			14
#define SOUND_FIRE_TOWER			15
#define SOUND_ICE_TOWER				16
#define SOUND_ELECT_TOWER			17
#define SOUND_BOSS_ALERT			18
#define SOUND_MONSTER_ALERT			19
#define SOUND_WALL_BEHIT			20
#define SOUND_WALL_BEHIT_BLAST		21
#define SOUND_MONSTER_BEHIT			22
#define SOUND_FIRE_MAGIC			23
#define SOUND_ICE_MAGIC				24
#define SOUND_WIND_MAGIC			25
#define SOUND_SUPER_MAGIC			26
#define SOUND_MAGIC_WAIT_FINISH		27
#define SOUND_MAIN_LOGO_EFFECT_FLY	28
#define SOUND_MAIN_LOGO_EFFECT_HIT	29

#endif